apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: travelapp
  name: travelapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travelapp
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: travelapp
    spec:
      containers:
      - image: 167359291143.dkr.ecr.ap-southeast-1.amazonaws.com/travelapp:latest
        name: travelapp
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "250Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: docker-secret
---
apiVersion: v1
kind: Service
metadata:
  name: travelapp-service
spec:
  selector:
    app: travelapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort


---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: travelapp-ingress
spec:
  rules:
  - host: rajesh.shop
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: travelapp-service
            port:
              number: 80





